# Generated by Django 3.0.3 on 2020-03-22 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='game_id',
            field=models.IntegerField(default=1),
        ),
    ]
